name: 'AI PR Auditor'
description: 'Automatically reviews Pull Requests using Google Gemini AI'
author: 'Ayushmaan-dev'

inputs:
  gemini-api-key:
    description: 'Google Gemini API Key'
    required: true
  github-token:
    description: 'GitHub Token for posting comments'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node24'
  main: 'dist/index.js'
